/*
 * Titulo: Panatalla 4 Módulo paciente.
 * Este programa se realizó para la organización "La sagrada familia A.C".
 * Esta panatalla consiste en el envio de emails adjuntando archivos.
 * Fecha: 24/03/2017
 */
package pantallas;

import clases.Controlador;
import clases.Correo;
import java.awt.Font;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Wicho
 */
public class FrmCorreo extends javax.swing.JFrame {

    Font fntTitulo = new Font("Tahoma", Font.BOLD, 24);
    Font fntComponente = new Font("Tahoma", Font.BOLD, 14);
    String docAdjunto = "";
    String rutaDocAdjunto = "";

    /**
     * Creates new form FrmCorreo
     */
    public FrmCorreo() {
        initComponents();
        skin();
    }

    private void skin() {
        lblAsunto.setText(lblAsunto.getText().toUpperCase());
        lblDestinatario.setText(lblDestinatario.getText().toUpperCase());
        lblMensaje.setText(lblMensaje.getText().toUpperCase());
        btnArchivo.setText(btnArchivo.getText().toUpperCase());
        btnEnviar.setText(btnEnviar.getText().toUpperCase());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblAsunto = new javax.swing.JLabel();
        lblDestinatario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaMensaje = new javax.swing.JTextArea();
        btnArchivo = new javax.swing.JButton();
        lblMensaje = new javax.swing.JLabel();
        txtAsunto = new javax.swing.JTextField();
        txtDestinatario = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        txtDocumento = new javax.swing.JTextField();
        lblDocumento = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuCorreo = new javax.swing.JMenu();
        mitHistorial = new javax.swing.JMenuItem();
        mitResponsables = new javax.swing.JMenuItem();
        mitPacientes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(198, 253, 188));

        lblAsunto.setFont(fntComponente);
        lblAsunto.setText("Asunto:");

        lblDestinatario.setFont(fntComponente);
        lblDestinatario.setText("Destinatario:");

        txaMensaje.setColumns(20);
        txaMensaje.setFont(fntComponente);
        txaMensaje.setRows(5);
        jScrollPane1.setViewportView(txaMensaje);

        btnArchivo.setFont(fntComponente);
        btnArchivo.setText("Archivo");
        btnArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArchivoActionPerformed(evt);
            }
        });

        lblMensaje.setFont(fntComponente);
        lblMensaje.setText("Mensaje:");

        txtAsunto.setFont(fntComponente);

        txtDestinatario.setFont(fntComponente);

        btnEnviar.setFont(fntComponente);
        btnEnviar.setText("Enviar");
        btnEnviar.setMaximumSize(new java.awt.Dimension(63, 40));
        btnEnviar.setMinimumSize(new java.awt.Dimension(63, 40));
        btnEnviar.setPreferredSize(new java.awt.Dimension(63, 40));
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        txtDocumento.setFont(fntComponente);

        lblDocumento.setFont(fntComponente);
        lblDocumento.setText("Documento:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblMensaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnArchivo)
                .addGap(101, 101, 101))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 91, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDestinatario)
                            .addComponent(lblAsunto, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDocumento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(263, 263, 263)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAsunto)
                    .addComponent(txtAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDestinatario)
                    .addComponent(txtDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDocumento)
                        .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMensaje)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        mnuCorreo.setText("Menú Correo");

        mitHistorial.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        mitHistorial.setText("Historial de salidas y entradas");
        mitHistorial.setToolTipText("");
        mitHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitHistorialActionPerformed(evt);
            }
        });
        mnuCorreo.add(mitHistorial);

        mitResponsables.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        mitResponsables.setText("Responsables de pacientes");
        mitResponsables.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitResponsablesActionPerformed(evt);
            }
        });
        mnuCorreo.add(mitResponsables);

        mitPacientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        mitPacientes.setText("Pacientes");
        mitPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitPacientesActionPerformed(evt);
            }
        });
        mnuCorreo.add(mitPacientes);

        jMenuBar1.add(mnuCorreo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mitHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitHistorialActionPerformed
        dispose();
        FrmHistorial_Ingresos_Egresos frmhie = new FrmHistorial_Ingresos_Egresos();
        frmhie.setVisible(true);
    }//GEN-LAST:event_mitHistorialActionPerformed

    private void mitResponsablesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitResponsablesActionPerformed
        dispose();
        FrmPacientes2 frm2 = new FrmPacientes2();
        frm2.setVisible(true);
    }//GEN-LAST:event_mitResponsablesActionPerformed

    private void mitPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitPacientesActionPerformed
        dispose();
        FrmPacientes frm = new FrmPacientes();
        frm.setVisible(true);
    }//GEN-LAST:event_mitPacientesActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:
        if (!txtDestinatario.getText().isEmpty()) {
            if (!txaMensaje.getText().isEmpty()) {
                Correo c = new Correo();
                Controlador con = new Controlador();
                c.setContrasena("degiepcliavtiwmd");
                c.setUsuarioCorreo("teifitvbot@gmail.com");
                c.setAsunto(txtAsunto.getText());
                c.setDestino(txtDestinatario.getText());
                c.setNombreArchivo(docAdjunto);
                c.setRutaArchivo(rutaDocAdjunto);
                c.setMensaje(txaMensaje.getText());
                if (con.enviarCorreo(c)) {
                    JOptionPane.showMessageDialog(this, "Se ha enviado el correo exitosamente.");
                } else {
                    JOptionPane.showMessageDialog(this, "Hubo un error al enviar el correo. Revise su conexión "
                            + "a internet e intentelo nuevamente.");
                }
            } else {
                JOptionPane.showMessageDialog(this, "ERROR: Faltó colocar el mensaje.");
            }

        } else {
            JOptionPane.showMessageDialog(this, "ERROR: Para enviar el correo se requiere un destinatario.");
        }

    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArchivoActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        int option = fc.showOpenDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            docAdjunto = fc.getSelectedFile().getName();
            rutaDocAdjunto = fc.getSelectedFile().getPath();
            txtDocumento.setText(docAdjunto);
        }
    }//GEN-LAST:event_btnArchivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCorreo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArchivo;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAsunto;
    private javax.swing.JLabel lblDestinatario;
    private javax.swing.JLabel lblDocumento;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JMenuItem mitHistorial;
    private javax.swing.JMenuItem mitPacientes;
    private javax.swing.JMenuItem mitResponsables;
    private javax.swing.JMenu mnuCorreo;
    private javax.swing.JTextArea txaMensaje;
    private javax.swing.JTextField txtAsunto;
    private javax.swing.JTextField txtDestinatario;
    private javax.swing.JTextField txtDocumento;
    // End of variables declaration//GEN-END:variables
}
